### ISSUE TITLE
function call() : Unable to call resource with form data as input

### ISSUE THREAD

**Issue by vprdnew** [shah/traverse-urls#1]
HI @shah 

The `call` function is now able to use only json data as input. It is requred to able for sending Form Data also. I had tested by making some change on the function to get work it work for FormData

```
//line number starting 230

try {
        const response = await nf.default(url, {
            method: 'post',
            redirect: 'follow',
            timeout: options.fetchTimeOut,
         

>    body: postBodyPOJO,

            headers: {
                'User-Agent': options.userAgent.toString(),
                'Accept': 'application/json',
              

>   // 'Content-Type': 'application/json;charset=UTF-8',

            }
        });
```

The abaove changes works for me by acepting formdata as input .

**Comment by shah** [comment]
@vprdnew please suggest a test case so we can put it into `traverse-urls` test suite.
